@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package com.whammich.sstow.enchantment;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;